### ISSUE TITLE
bad request line 92

### ISSUE THREAD

**Issue by jeremykeen** [AndyRawson/SmartThings#1]
Trying to modify your code for the new particle name vs spark.  I get the error in ST logs:
groovyx.net.http.HttpResponseException: Bad Request @ line 92

My auth code looks like this:
httpPost(uri: "https://particle:particle@api.particle.io/oauth/token",
            body: [grant_type: "password", 
        username: particleUsername,
        password: particlePassword,
        expires_in: "157680000"] 
            ) {response -> state.particleToken = response.data.access_token
                }
        log.debug "Created new Particle.io token"  
        //log.debug "Particle Token ${state.particle22Token}"
        checkToken() 

Any thoughts? The httpPost is line 92.

**Comment by AndyRawson** [comment]
It looks like the problem is with sending particle:particle (or spark:spark) in the uri wasn't working anymore from SmartThings. I have found encoding it and passing it as an Authorization header does work.

```
   if (!state.sparkToken){
   def clientAuth = "particle:particle"
   clientAuth = "Basic " + clientAuth.encodeAsBase64().toString()
   def params = [
        headers: [Authorization: clientAuth],
        uri: "https://api.particle.io/oauth/token",
        body: [grant_type: "password", 
        username: sparkUsername,
        password: sparkPassword] 
        ]
   try {
        httpPost(params) {response -> 
            state.sparkToken = response.data.access_token
                }
    } catch (e) {
        log.error "error: $e"

    }
```

There are still several pieces of this SmartApp that weren't finished and I have not had time to spend on it. The whole thing needs a redesign since it kind of got out of hand while I was working on it but the basics are there.
